version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/api
permissions:
  - object: /usr/share/nginx/html/api
    owner: ubuntu
    group: www-data
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/install_nodejs_application
      timeout: 1000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_pm2_application
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_pm2_application
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_pm2_application
      timeout: 15
      runas: ubuntu